### ISSUE TITLE
docs: Update readme to include mandatory parameters for execution workflow

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#189]
Each execution workflow should have parameters on which benchmark to run in the config file. The parameters are:
run_identification = True/False
run_quantification = True/False
run_differential = True/False

Only parameters for benchmarks that the workflow qualifies for should be included. For example, if a workflow only qualifies for identification and differential, it should only include:
run_identification = True/False
run_differential = True/False

This allows for the workflow to output any combination of benchmarks that it qualifies for, as specified by the user.

Readmes to be updated:
Execution workflow readme
Nextflow template readme
Execution workflow dsl1 template readme
Execution workflow dsl2 template readme

**Comment by faricazjj** [comment]
@ninsch3000 @dominikburri @SamBryce-Smith @yuukiiwa @grexor @uniqueg Does this description sound like what we want to go ahead with following up from our meeting today?

**Comment by ninsch3000** [comment]
Thanks a lot @faricazjj .   
I think it could be useful to also mention that the ewfs might have to run a tool twice under the hood, or any other considerations for coding you have come across (You know better than me since you already wrote so many ewfs!!). I mean, just to give the reader some idea on what they might have to face. 
And as for "Readmes to be updated": Snakemake template should also be updated :)
