### ISSUE TITLE
docs: Output format in benchmark specifications doesn't agree with OEB

### ISSUE THREAD

**Issue by daneckaw** [iRNA-COSI/APAeval#211]
Output of summary workflows should be in OEB format. All benchmarks specifications need to be corrected.

**Comment by ninsch3000** [comment]
As discussed during the last meeting, the benchmarking specifications mainly describe the metrics to be calculated. Therefore, only `assessment.datasets.json` has to be described as output file in detail. Otherwise we'd have to include the whole OEB benchmarking data model, which is beyond the scope of the benchmarking specification and should rather be discussed on the community level. However, as it is relevant for the plotting, it should be mentioned that the plot type with it's corresponding metrics has to be specified in the aggregation file, which is called [CHALLENGE].json.   
The example file should look like this: (all metrics for one participant)   
```
[
    {
        "_id": "APAeval:datasetA_correlation_10nt_my_tool",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "correlation_coefficient_10nt",
            "value": 0.54
        },
        "participant_id": "my_tool",
        "type": "assessment"
    },
    {
        "_id": "APAeval:datasetA_correlation_50nt_my_tool",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "correlation_coefficient_50nt",
            "value": 0.85
        },
        "participant_id": "my_tool",
        "type": "assessment"
    },
    {
        "_id": "APAeval:datasetA_correlation_100nt_my_tool",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "correlation_coefficient_100nt",
            "value": 0.54
        },
        "participant_id": "my_tool",
        "type": "assessment"
    },
    {
        "_id": "APAeval:datasetA_[OTHER_METRIC]_10nt_my_tool",
    ...
]
```
