### ISSUE TITLE
utils: scripts for visualizing summary statistics outside OEB

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#245]
_This is a meta issue, several more specific issues will have to be created in order to complete the task_

We would like to compare results from different samples in ways which are not supported in OEB.

TO DO:
- [ ] define set of summary statistics and visualizations
- [x] parse json outputs from summary workflows for relevant metrics
- [ ] create visualizations 
- [ ] possibly more, as this is just a "meta issue"

**Comment by dominikburri** [comment]
You can have a look at the optional plots defined in this PR: https://github.com/iRNA-COSI/APAeval/pull/222.

**Comment by daneckaw** [comment]
Is the idea to run the scripts for calculating optional metrics separately from OEB summary workflows? Or to calculate everything within those summary workflows and then use generated JSON files to make additional plots?

**Comment by dominikburri** [comment]
> Is the idea to run the scripts for calculating optional metrics separately from OEB summary workflows? Or to calculate everything within those summary workflows and then use generated JSON files to make additional plots?

The idea is to use the generated json files containing the metrics to create additional plots. 
If new metrics are needed, then those need to be calculated separately. If this is the case, the summary workflow could be used as a template maybe, in particular the `compute_metrics.py`. Not the whole nextflow workflow would be needed.

So we probably have an additional directory like `additional_plots` that contains scripts for plotting and maybe also some scripts for calculating new, unseen metrics.

**Comment by ninsch3000** [comment]
Good question @daneckaw . I personally would go with calculating all metrics in the same SWF and then parsing the JSON files. The SWFs can be used independently of OEB, so it makes sense to have all APAeval metrics in the same workflow, especially since some functions are shared between different metric calculations. Like that we'd also have to run fewer workflows in total (with the amount of tools and challenges running all workflows will be tedious). And also when the workflows are used within OEB, the additional metrics can be stored in the DB, even if they are currently not visualized. Like that, if you download the data from the OEB DB you'd have all metrics in one place.    

@dominikburri just stated the opposite opinion :) So maybe we could hear some more thoughts, e.g. @txellferret , @daneckaw , @SamBryce-Smith , @AsierGonzalez

**Comment by txellferret** [comment]
I agree that it is better to have all in the same workflow, so the resulted data will be in OEB even though it is not visualized as a plot right now, but maybe in the future and can be accessible by API.

**Comment by grexor** [comment]
Perhaps the simplest way to handle this is to define more concretely what needs to be done, for a start:

* example input (JSON)
* example output (graph)

:-)

**Comment by daneckaw** [comment]
I'm not sure how compatible some calculations are with OEB data format. For example if you look at [identification specifications](https://github.com/iRNA-COSI/APAeval/blob/main/summary_workflows/identification/specification/I_benchmark_specification.md), optional plot 2: we'd have to calculate and store values of sensitivity and precision for all window size values. I'm not sure if it's possible to store an array of values, and if not, each value would have to be a separate metric with its own name. Which is not a technical problem, but maybe it makes the files a bit bloated?

**Comment by dominikburri** [comment]
Ok I try to come up with a simple example to visualise the working of computing metrics with or without OEB.

# Data
The example BED files are from [here](https://github.com/iRNA-COSI/APAeval/blob/474f80976e950f78e677f4c1852ac3e4dab4fec4/summary_workflows/quantification/APAeval_Q_test_data/test.mm10_test.bed) and [here](https://github.com/iRNA-COSI/APAeval/blob/474f80976e950f78e677f4c1852ac3e4dab4fec4/summary_workflows/quantification/APAeval_Q_test_data/metrics_ref_datasets/test.mm10_test.gt.bed) .

## Test:
```tsv
chr1	3199734	3199735	not_in_gt	156.240540124	-
chr1	4490931	4490932	chr1_r_c30	3.90601350309	-
chr1	4781398	4781399	chr1_r_c41	4.88251687886	-
chr1	4846733	4846734	chr1_f_c15	16.1123057002	+
chr1	4909575	4909576	chr1_r_c47	8.30027869406	-
chr1	5162444	5162445	chr1_f_c30	219.713259549	+
chr1	6275164	6275165	two_gt	60.0131417824	+
chr1	6275576	6275577	chr1_f_c55	26.8538428337	+
chr1	6276374	6276375	same_gt_1	20.4360810185	+
chr1	6276378	6276379	same_gt_2	5.4360810185	+
```

## ground truth
```tsv
chr1	2199734	2199735	not_in_pd	156.240540124	-
chr1	4490931	4490932	chr1_r_c30	3.90601350309	-
chr1	4781398	4781399	chr1_r_c41	4.88251687886	-
chr1	4846733	4846734	chr1_f_c15	16.1123057002	+
chr1	4909575	4909576	chr1_r_c47	8.30027869406	-
chr1	5162444	5162445	chr1_f_c30	219.713259549	+
chr1	6275160	6275161	same_pd_1	21.9713259549	+
chr1	6275165	6275166	same_pd_2	41.0131417824	+
chr1	6275576	6275577	chr1_f_c55	26.8538428337	+
chr1	6276374	6276375	two_pd	23.4360810185	+
```

# Metrics

Let's follow @daneckaw's example and we want to calculate sensitivity and precision for window sizes `range(0,201,10)`. This would give us 21 values for sensitivity and 21 for precision which would be plotted in a line plot like in [this example](https://www.researchgate.net/figure/Precision-Recall-rate-curve-example_fig1_331675538).
Now it depends whether we follow OEB, then we have to store them in a specific json format, or we calculate on our own and have more freedom.

These metrics can be computed with the two BED files above 

## OEB specific
Basically, the additional metrics have to be computed within a python script that would be packaged into a Docker image and ran on the VRE platform. E.g. [here](https://github.com/iRNA-COSI/APAeval/blob/474f80976e950f78e677f4c1852ac3e4dab4fec4/summary_workflows/quantification/quantification_dockers/q_metrics/compute_metrics.py). 
Let's say we did this and have the metrics, they would look something like (taken from [here](https://github.com/iRNA-COSI/APAeval/blob/474f80976e950f78e677f4c1852ac3e4dab4fec4/summary_workflows/identification/specification/example_files/assessment_out.json)):
```json
[
    {
        "_id": "APAeval:datasetA_toolA_Precision_0nt",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "Precision_0nt",
            "stderr": 0,
            "value": 0.54
        },
        "participant_id": "toolA",
        "type": "assessment"
    },
    {
        "_id": "APAeval:datasetA_toolA_Precision_10nt",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "Precision_10nt",
            "stderr": 0,
            "value": 0.85
        },
        "participant_id": "toolA",
        "type": "assessment"
    },
...
{
        "_id": "APAeval:datasetA_toolA_Precision_200nt",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "Precision_200nt",
            "stderr": 0,
            "value": 0.85
        },
        "participant_id": "toolA",
        "type": "assessment"
    },
    {
        "_id": "APAeval:datasetA_toolA_Sensitivity_0nt",
        "challenge_id": "datasetA",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "Sensitivity_0nt",
            "stderr": 0,
            "value": 0.76
        },
        "participant_id": "toolA",
        "type": "assessment"
    },
    {
        "_id": "APAeval:datasetA_toolA_Sensitivity_10nt",
        "challenge_id": "datasetB",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "Sensitivity_10nt",
            "stderr": 0,
            "value": 0.81
        },
        "participant_id": "toolA",
        "type": "assessment"
    }
...
{
        "_id": "APAeval:datasetA_toolA_Sensitivity_200nt",
        "challenge_id": "datasetB",
        "community_id": "APAeval",
        "metrics": {
            "metric_id": "Sensitivity_200nt",
            "stderr": 0,
            "value": 0.81
        },
        "participant_id": "toolA",
        "type": "assessment"
    }
]
```
where `...` means I skipped each 18 entries. 

Now each of the `value` of the metric IDs have to be read out in order to make our desired plots. 
Also, all these values will be calculated each time the workflow is triggered on the VRE.

## independent version

As it suggests, your are independent in calculating the metrics. For me it is easiest to do in python, maybe even in the same way as in the OEB version, but I would be free in how to save them. 
Let's again say I have a function that takes two BED files and computes sensitivity and one that computes precision, each giving a scalar back. I could save it in a dataframe which looks conceptually like:

window_size | sensitivity | precision 
--- | --- | --- 
0 | 0.4 | 0.9
10 | 0.5 | 0.8
... | ... | ...
200 | 0.9 | 0.1

where the triple dots skip 18 rows. 
> Note: this table can of course be obtained from the json format above.

# Summary

- in both versions, we obtain the same metric values, once just in a specific json format, once freely.
- the plotting function is independent of OEB (because they don't support such plots).
- The difference comes from **where** it is computed: in a docker container on VRE or own scripts
- and thus how much code duplication we want; using only one code base or duplicate possibly some metric calculation. 

So I think we need to make the decision before we start, as otherwise the code would need to be re-written quite a bit.
I don't have strong preference, but I lean towards own calculations as the possibility of messing up the swf is not there (e.g. what if we need a different genome annotation, maybe gff? how to incorporate this in a production swf?). But I don't like the duplication of code, e.g. some metrics are already calculated, just not for that many window sizes. So we could of course base the new on the existing one. 
I hope I made thinks a bit clearer.

**Comment by ninsch3000** [comment]
Has been solved in Jupyter notebooks for the manuscript publication for now
