### ISSUE TITLE
Identification summary workflow: implement annotation-dependent and other metrics

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#298]
Ensure that annotation-dependent metrics (similar as the one in quantification summary workflow) and other metrics are implemented in identification summary workflow

parent issue: https://github.com/iRNA-COSI/APAeval/issues/239

Estimate: 4h

**Comment by dominikburri** [comment]
PR #421 implements the bulk of identification metrics. Pointer for missing metrics: https://github.com/iRNA-COSI/APAeval/pull/421#issuecomment-1245208755.

Will create new branch on top of `swf_ident_new` for remaining metrics.

**Comment by dominikburri** [comment]
Compute metric nr. 5 in commit a6ef401.
This reports the percentage of genes with correctly identified number of PAS. 
How I interpreted and calculated it: 

- For ground truth (GT) and prediction (PD) PAS sites independently, find all PAS for each gene from the genome with `find_pas_genes` in utils.
- Count the number of PAS per gene, again independently for GT and PD.
- Count the number of genes where the number of PAS is identical in GT and PD AND where the number of PAS in GT is > 0. 
- The fraction of number of genes with identical PAS numbers and the number of genes with > 0 PAS.
- The final percentage is the fraction times 100.  

Some notes

- This approach does not rely on PAS matching, it first checks for each gene the number of PAS and then compares it.
- It also does not depend on window size, so the metric name is - as the _AUC_ measure - without `window`.
- The percentage is calculated with non-zero PAS genes from GT in mind. If this is not intended, I could also compute it against all genes. I decided against this, as the majority of genes had 0 PAS from the GT BED file (meaning not all genes are expressed in a sample). So, we would get a lot of matches (0 PAS genes on GT and PD) normalised by a lot of genes (which would dilute the measure I think).

**Comment by mrgazzara** [comment]
@dominikburri This looks good and properly computes what I would understand this metric to be. 

I do see one problem, at least with the DaPars/DaPars2 outputs (perhaps other tools as well?). PAS in the output `bed`, from DaPars, at least are not unique. The same distal or proximal PAS can be represented multiple times because they are associated with different transcripts. Because we only check for overlap between the prediction PAS and the gene annotation using `chromosome`, `start`, `stop`, and `strand` the `PD` counts will be inflated for such tools.  I will make a comment in commit a6ef401 where I think we can fix this.

**Comment by dominikburri** [comment]
Thanks @mrgazzara, I included a commit with your suggestions. 
Also created a draft PR #432 with the remaining metric (genome features).
