### ISSUE TITLE
Mapping/remapping of RNA-seq data

### ISSUE THREAD

**Issue by faricazjj** [iRNA-COSI/APAeval#302]

**Comment by ninsch3000** [comment]
I confirm @dominikburri 's "anecdotal" observation, that samples seem to map okish to chr1, but on other chromosomes either don't map or totally mismatch.
I looked at SRR6795718, SRR6795713 (both Mayr) and SRR1573494 (NOT Mayr, so the samples don't seem to be at fault).    

For the re-mapped files, can we get some mapping statistics and quality reports? Are you using nf-core/rnaseq? They should have these kind of reports, don't they? If not, you might want to consider using a different pre-processing pipeline, as I think it is important (especially for a benchmarking paper) to provide provenance and quality information about the utilized data. Along the same lines, we need to know *exactly* which genome version/files have been used.

**Comment by mrgazzara** [comment]
@ninsch3000 Yes the problem was with the headers in the bam files. The provenance of the files uploaded to the public facing server is questionable (we have moved around form computing resources many times in the past year), it is more than likely the wrong set of files were grabbed. 

I have been in the process of remapping everything with nf-core/rnaseq again. I am writing up a good description / documentation of exactly how things are run, etc. and will post a full description with links to the results above soon.

**Comment by mrgazzara** [comment]
Mapping is complete. I will upload and review the MultiQC results (which nicely collects many QC metrics in one spot) and update the bam files on the public facing server tomorrow

**Comment by mrgazzara** [comment]
Upload is complete. Finalized bam files can be found here: [https://majiq.biociphers.org/data/apaeval/bams/](https://majiq.biociphers.org/data/apaeval/bams/) with description of samples in the [datasets GSheet RNA-seq tab](https://docs.google.com/spreadsheets/d/1iZ-4RknIfLsfBJ8ank6w9JrkeVq0PEvoeLbtKUwghmA/edit#gid=899136187&range=A1). 

Closing this issue!
