### ISSUE TITLE
Execution Workflow: CSI-UTR

### ISSUE THREAD

**Issue by ninsch3000** [iRNA-COSI/APAeval#31]
## WHAT    
**Write** execution workflow for [CSI-UTR](https://github.com/UofLBioinformatics/CSI-UTR). Use the provided [small files for testing](https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data) (running the workflow on real data is a different issue).

## CHECKLIST   
* [x] Use [snakemake template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/snakemake) or [nextflow template](https://github.com/iRNA-COSI/APAeval/tree/main/docs/templates/nextflow) to create your workflow.
* [ ] Comment your code
* [x] Run individual rules/processes in either conda envs or docker/singularity containers for reproducibility
* [x] Input:  .bam or .fastq from [test_data]((https://github.com/iRNA-COSI/APAeval/tree/main/tests/test_data))
* [ ] Give [feedback about the method](https://forms.gle/mAAkbRJqhedJnSeJ6)

## OUTPUTS (see [specification](https://github.com/iRNA-COSI/APAeval/blob/main/execution_workflows/execution_output_specification.md)): 
* [ ] Does CSI-UTR perform PAS identification? If yes:
* [ ] Output: Adhere to output specification for Identification challenge
     > This BED file contains single-nucleotide position of poly(A) sites identified by the tool.
Fields:

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - not used, leave as "."
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for quantification challenge
     > This BED file contains positions of unique poly(A) sites with TPM values for each identified site in the score column.

    > chrom - the name of the chromosome
    chromStart - the starting position of the feature in the chromosome
    chromEnd - the ending position of the feature in the chromosome; as identified PAS are single-nucleotide, the ending position is the same as starting position
    name - defines the name of the identified poly(A) site
    score - TPM value for the identified site
    strand - defines the strand; either "." (=no strand) or "+" or "-".

* [ ] Output: Adhere to output specification for differential usage challenge
   > This TSV file contains two columns:

    > - gene ID
    > - significance of differential PAS usage

    > Column names should not be added to the file.

**Comment by SamBryce-Smith** [comment]
Hey @MelinaKlostermann 

Just wanted to check if you're still going to be able to contribute to this workflow? Absolutely not a problem if not (though would be great if you still want to help out!), it's mainly so the rest of the group know what still needs to be done.

Also, if you've managed to make any progress so far it would be great to see any of your code pushed, even if it's still a work in progress! Most of all you'll get credit for your work but then others can join in too without starting from scratch.

Thanks :)

**Comment by SamBryce-Smith** [comment]
Thanks @MelinaKlostermann for your work so far! The pipeline needs someone to volunteer to complete it, part of the pipeline has already been written in nextflow.

If you want to volunteer, assign yourself and pick up where it was left off on `MelinaKlostermann-patch-1` :)

**Comment by faricazjj** [comment]
Currently blocked on this because of the following issue:

In line 226, https://github.com/UofLBioinformatics/CSI-UTR/blob/master/CSI-UTR_v1.1.0/bin/CSI-UTR there's an error thrown regardless of whether we specify the flag 'annot' with the path to an annotation file. This is because in the code, the annotation file path is hardcoded to './data/annotations/$genome.CSIs.annot.bed' where $genome is the value specified by the 'genome' flag (e.g Mm10 in our case).

similar to the annotation file issue above, in line 255, it hardcodes bed file to './data/locations/$genome.CSIs.bed', even though there is a flag to specify the path to the bed file. 

The hardcoded path works if we download the repo that includes the 'data' folder that they require.

So currently, we have the following error message:
Command error:
  ERROR IN ANNOTATION FILE: ./data/annotations/Mm10.CSIs.annot.bed DOES NOT EXIST at /CSI-UTR/CSI-UTR_v1.1.0/bin/CSI-UTR line 226.

Work dir:
  /Users/fzhuang/Desktop/APAeval/APAeval/execution_workflows/CSI-UTR/work/86/860929d50f1cd1317781d99354f23a


I've contacted the author to check these two things:
1. Is there an option that I missed to not use the hardcoded path and instead our own annotation and bed file?
2. Do we have to use the provided annotation and bed files?

Things I've tried to get around this hardcode issue:
1. Moving data folder to have access to annotation and bed files from docker container home
RUN mv /CSI-UTR/CSI-UTR_v1.1.0/data .
This works when we go into the container and run CSI-UTR from the home directory. But on nextflow the data folder is still not found.

2. Tried putting 'data folder 'in CSI-UTR in APAeval so that it's accessible by nextflow 
Still didn't work

3. Tried renaming the bed file obtained from converting our gtf file to './data/Mm10.CSIs.annot.bed'
Line 22 of convert_gtf_to_bed
converted_genome_file = "./data/annotations/Mm10.CSIs.annot.bed"
Got an error Command error:
  mustOpen: Can't open ./data/annotations/Mm10.CSIs.annot.bed to write: No such file or directory


The only way seems to be if the path is not hardcoded in their code so that we can customize our own path that nextflow can access.

Will update when there's a reply from the author.

@SamBryce-Smith

**Comment by SamBryce-Smith** [comment]
Thanks so much for this, hopefully you get a response from the authors soon! I can't see anything obvious to try out from your description (though Nextflow & Docker are outside my expertise) either. 

So just to double check I've got this right though; it seems like the command line flags to set the input BED and 'genome' files (e.g. [like here in the usage](https://github.com/UofLBioinformatics/CSI-UTR/blob/fbcdb820ee7773c4873d28f5645af1daae13d89a/CSI-UTR_v1.1.0/bin/CSI-UTR#L301)) do not work at all, and if you try to manually move input files to the hardcoded location Nextflow throws errors (can't find the files)? So, it's not clear whether we can provide our own annotation files (e.g. starting with a GTF & set of reference PAS sites) (or even how to generate them, though the [paper](https://www.frontiersin.org/articles/10.3389/fgene.2019.00182/full#h3) seems to go into more detail than the Github from a brief browse).

**Comment by faricazjj** [comment]
Following up on the bugs found above, I've created an issue reporting these bugs on CSI-UTR repo https://github.com/UofLBioinformatics/CSI-UTR/issues/3. We're able to get around the bugs on nextflow, hence the workflow works, but the bugs still not addressed by the authors.

@SamBryce-Smith
