### ISSUE TITLE
 incosistent envs for calls to snakemake nextflow

### ISSUE THREAD

**Issue by mkatsanto** [iRNA-COSI/APAeval#59]
From earlier discussion the issue arised, that nextflow and snakemake are executed from different (incosistent) conda environments specifications.
To solve this I need to 

- [ ] Modify the snakemake.yml to environment.yml and add both snakemake and nextflow specific versions
- [ ] Replace the nextflow env from the templates

I can not find the conda env from which nextflow is triggered, can someone point it out? Is such an environment needed in the context of nextflow? @uniqueg @dominikburri @yuukiiwa

**Comment by yuukiiwa** [comment]
Ideally, `nextflow` does not use a `conda` environment but instead uses the docker image generated based on the packages list on `environment.yml`.

**Comment by mkatsanto** [comment]
If I understand correctly these docker images refer to the execution of the different nextflow parts. I meant the conda env through which you make the call to nextflow in the first place. Is there a generic conda with some predefined python versions and nextflow versions? Would it make sense to have one?

**Comment by yuukiiwa** [comment]
I don't think you have to install `nextflow` within the `conda` environment, but instead, you install `nextflow` on your machine and run your pipeline with `nextflow main.nf -profile docker --input [file] ...` (this is from my experience contributing to `nf-core`). And, assuming the pipeline will likely be executed on `Nextflow Tower`, which is `nextflow`-specific and should have `nextflow` installed in its backend. Therefore, your docker container containing the software/tools used in the processes should be sufficient. The `environment.yml` file in the `nextflow_dsl1` template covers all software/tools in the pipeline while `nextflow dsl2` requires each process module to have its own docker container.

**Comment by ninsch3000** [comment]
I thought we'd like to have like a main APAeval conda env, that everybody can use to ensure we're all working with the same versions of snakemake and nextflow (and possibly other widely used tools like samtools or bedtools). Of course the rule/process specific envs - actually we agreed on using containers, not conda envs - are a different story, because the tools to be benchmarked might all require different python versions for example.
Am I completely on the wrong track here? :)

**Comment by yuukiiwa** [comment]
I think what you have said is on the right track, @ninsch3000! Yes, a central `conda` environment is needed so that everyone is using the same `snakemake` and `nextflow`. However, the `environment.yml` provided in the `nextflow_dsl1` template is for creating the docker container for the pipeline only not for the central `conda` env. So it may potentially be looking like running a dockerized pipeline within a `conda` environment with the specific `snakemake` and `nextflow`  versions.
